apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler
  namespace: myscheds # Specify the namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-scheduler
  template:
    metadata:
      labels:
        app: custom-scheduler
    spec:
      containers:
      - name: custom-scheduler
        image: swapnil333/custom-scheduler:latest
